### A Pluto.jl notebook ###
# v0.20.4

using Markdown
using InteractiveUtils

# ╔═╡ 0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4d01
begin
    import Pkg
    Pkg.develop(path=joinpath(@__DIR__, "..", "EpiParameters"))
    Pkg.develop(path=expanduser("~/code/EpiNow2.jl"))
    using EpiNow2
    using EpiParameters
    using Distributions
    using DataFrames
    using Dates
    using CairoMakie
end

# ╔═╡ 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5d01
md"""
# Quantifying Transmission

The transmission intensity of an outbreak is quantified using two key metrics:

- The **reproduction number** measures the *strength* of transmission — how many new cases each existing case generates on average.
- The **growth rate** measures the *speed* of transmission — how rapidly the outbreak is spreading or declining, related to the doubling time (when growing) or halving time (when declining).

The **basic reproduction number** $R_0$ is the average number of secondary cases generated by a single infected individual in a fully susceptible population. It characterises the pathogen's intrinsic transmissibility.

The **effective reproduction number** $R_t$ accounts for changes over time: population immunity, behavioural changes, and interventions all affect how many secondary infections each case actually produces at time $t$.

- $R_t > 1$: epidemic is growing
- $R_t < 1$: epidemic is shrinking
- $R_t = 1$: epidemic is stable

To estimate these metrics from case data, we must account for delays between infection and reporting. The time-varying reproduction number $R_t$ is therefore not simply a ratio of case counts, but requires statistical estimation that properly handles these delays and the inherent stochasticity of transmission.

**EpiNow2.jl** uses a **Bayesian inference** framework to estimate $R_t$. It combines prior knowledge (expressed as prior distributions on parameters) with observed data (via the likelihood) to produce posterior distributions for $R_t$ and other quantities of interest. This naturally quantifies uncertainty in our estimates — rather than producing a single point estimate, we obtain a full distribution reflecting what the data tell us.

This tutorial covers:
1. Estimating $R_t$ from case data using **EpiNow2.jl**
2. Specifying delay distributions (generation time, reporting delays)
3. Interpreting the output

!!! warning "Computation time"
    MCMC sampling takes several minutes. Be patient while the model runs.
"""

# ╔═╡ 2a3b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6d01
md"""
## The data

In an outbreak situation, data are usually available on reported dates only — we rarely know the true date of infection. We must therefore use estimation methods that account for delays between infection and reporting when trying to understand changes in transmission over time.

Here we use synthetic case data built into EpiNow2.jl — 60 days of daily confirmed cases generated from a renewal process with time-varying $R_t$:
"""

# ╔═╡ 3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7d01
cases = example_confirmed()

# ╔═╡ 4a5b6c7d-8e9f-0a1b-2c3d-4e5f6a7b8d01
let
    fig = Figure(size=(700, 300))
    ax = Axis(fig[1, 1]; xlabel="Date", ylabel="Confirmed cases",
              title="Daily confirmed cases")
    barplot!(ax, 1:nrow(cases), cases.confirm; color=(:steelblue, 0.7))
    ax.xticks = (1:10:nrow(cases), string.(cases.date[1:10:end]))
    ax.xticklabelrotation = π/4
    fig
end

# ╔═╡ 5a5b6c7d-8e9f-0a1b-2c3d-5e5f6a7b8d01
md"""
## Specifying delay distributions

To estimate $R_t$, EpiNow2 needs to know about the delays involved in the observation process. Why distributions rather than point estimates? The delay from infection to report involves multiple biological and administrative processes, each with individual-level variation. We capture this variation with probability distributions rather than fixed values, which properly propagates uncertainty into our $R_t$ estimates.

The key delays are:

1. **Generation time** — the delay between infection of a primary case and
   infection of a secondary case. This determines the timescale of transmission.
2. **Reporting delays** (optional) — incubation period + time from symptom onset
   to case confirmation. These determine how reported cases relate to the
   underlying infection process.

The delay from infection to report is composed of multiple stages: infection → symptom onset (the **incubation period**) followed by symptom onset → case notification (the **reporting delay**). Since delays cannot be negative, we use distributions defined on positive values only, such as the Gamma or LogNormal distributions.

Which delays you need depends on the data source:

| Data source | Delay(s) needed |
|---|---|
| Time of symptom onset | Incubation period |
| Time of case report | Incubation period + reporting delay |
| Time of hospitalisation | Incubation period + onset-to-hospitalisation |

We specify these as discretised probability distributions.

### Generation time

Let's use a LogNormal generation time with mean ≈ 3.6 days:
"""

# ╔═╡ 6a7b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0d01
generation_time = discretise(LogNormal(1.2, 0.5); max=14)

# ╔═╡ 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1d01
md"""
### Incubation period + reporting delay

We can compose delays with `+`:
"""

# ╔═╡ 8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2d01
begin
    incubation = discretise(LogNormal(1.4, 0.4); max=14)
    reporting = discretise(LogNormal(0.5, 0.5); max=7)
    total_delay = incubation + reporting
end

# ╔═╡ 9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3d01
md"""
## Running the estimation

Now we call `epinow()` — the main entry point. We use lighter inference settings
for this tutorial (fewer samples and chains):
"""

# ╔═╡ aa1b2c3d-4e5f-6a7b-8c9d-ae1f2a3b4d01
result = epinow(cases;
    generation_time = gt_opts(generation_time),
    delays = delay_opts(total_delay),
    rt = rt_opts(prior=LogNormal(log(1.0), 1.0)),
    inference = inference_opts(samples=1000, warmup=200, chains=2,
                               progress=false),
    verbose = false)

# ╔═╡ ab1b2c3d-4e5f-6a7b-8c9d-ab1f2a3b4d01
md"""
EpiNow2 performs Bayesian inference using Markov chain Monte Carlo (MCMC) methods via Turing.jl. Under the hood, the model uses a **renewal equation** to link infections over time through the generation time distribution: the expected number of new infections on each day is the sum of past infections weighted by the generation time probability mass function, scaled by $R_t$. A **Gaussian process** is used to smooth $R_t$ over time, preventing implausibly rapid changes while still allowing it to capture genuine trends.

Running multiple MCMC chains (as we did above with `chains=2`) helps assess whether the sampler has converged — if chains starting from different initial values reach similar posterior distributions, we can be more confident in the results.
"""

# ╔═╡ ba2b3c4d-5e6f-7a8b-9c0d-be2f3a4b5d01
md"""
## Interpreting the results

The result contains estimates of $R_t$, infections, and predicted reports, each as a DataFrame with credible intervals.

The output estimates are split into three categories:

- **Estimate**: based on complete data — all delays have had time to resolve, so these are the most reliable estimates.
- **Estimate based on partial data**: recent time points where some infections that occurred may not yet have been reported. These estimates have higher uncertainty because the most recent infections are least likely to have been observed.
- **Forecast**: projections into the future assuming $R_t$ remains constant at its most recent estimated value.

The uncertainty in the estimates naturally grows towards the end of the time series, reflecting the fact that recent data are incomplete:
"""

# ╔═╡ ca3b4c5d-6e7f-8a9b-0c1d-ce3f4a5b6d01
result.estimates.rt

# ╔═╡ da4b5c6d-7e8f-9a0b-1c2d-de4f5a6b7d01
md"""
### Reproduction number over time
"""

# ╔═╡ ea5b6c7d-8e9f-0a1b-2c3d-ee5f6a7b8d01
let
    rt = result.estimates.rt
    fig = Figure(size=(700, 350))
    ax = Axis(fig[1, 1]; xlabel="Date", ylabel="Rt",
              title="Time-varying reproduction number")

    dates_idx = 1:nrow(rt)

    # 90% CrI
    band!(ax, dates_idx, rt.lower_90, rt.upper_90; color=(:steelblue, 0.15))
    # 50% CrI
    band!(ax, dates_idx, rt.lower_50, rt.upper_50; color=(:steelblue, 0.3))
    # Median
    lines!(ax, dates_idx, rt.median; linewidth=2, color=:steelblue)

    hlines!(ax, [1.0]; color=:red, linestyle=:dash, linewidth=1.5)
    text!(ax, nrow(rt), 1.02; text="Rt = 1", align=(:right, :bottom),
          fontsize=10, color=:red)

    ax.xticks = (1:10:nrow(rt), string.(rt.date[1:10:end]))
    ax.xticklabelrotation = π/4

    fig
end

# ╔═╡ eb5b6c7d-8e9f-0a1b-2c3d-eb5f6a7b8d01
md"""
In all EpiNow2 output figures, the shaded regions represent **credible intervals** — darker shading indicates higher confidence. The 50% credible interval (darker band) contains the most likely values, whilst the 90% credible interval (lighter band) captures most of the uncertainty. The dashed red line at $R_t = 1$ marks the threshold between a growing and a shrinking epidemic.
"""

# ╔═╡ fa6b7c8d-9e0f-1a2b-3c4d-fe6f7a8b9d01
md"""
### Estimated infections vs reported cases
"""

# ╔═╡ 0b7b8c9d-0e1f-2a3b-4c5d-0f7f8a9b0d01
let
    inf = result.estimates.infections
    rep = result.estimates.reports

    fig = Figure(size=(700, 350))
    ax = Axis(fig[1, 1]; xlabel="Date", ylabel="Count",
              title="Estimated infections and predicted reports")

    # Infections
    band!(ax, 1:nrow(inf), inf.lower_90, inf.upper_90; color=(:steelblue, 0.15))
    lines!(ax, 1:nrow(inf), inf.median; linewidth=2, color=:steelblue,
           label="Infections (estimated)")

    # Observed cases
    obs_dates = [findfirst(==(d), inf.date) for d in cases.date]
    obs_idx = filter(!isnothing, obs_dates)
    scatter!(ax, obs_idx, cases.confirm[1:length(obs_idx)]; markersize=5,
             color=:black, label="Observed cases")

    ax.xticks = (1:10:nrow(inf), string.(inf.date[1:10:end]))
    ax.xticklabelrotation = π/4
    axislegend(ax; position=:lt)

    fig
end

# ╔═╡ 1b8b9c0d-1e2f-3a4b-5c6d-1f8f9a0b1d01
md"""
## Using delay distributions from the literature

Instead of specifying delays manually, we can pull them from `EpiParameters.jl`. Using literature-sourced delay distributions is particularly valuable early in an outbreak, when local data on delays may not yet be available — published estimates from previous outbreaks or other settings provide a reasonable starting point.

```julia
using EpiParameters

# Get COVID-19 generation time from the literature
gt_results = epiparameter(disease="COVID-19", epi_name="serial interval")
gt_dist = filter(p -> !isnothing(p.distribution), gt_results)[1].distribution

# Discretise and use in EpiNow2
generation_time = discretise(gt_dist; max=14)
result = epinow(cases; generation_time=gt_opts(generation_time), ...)
```

The next tutorial covers this workflow in detail.
"""

# ╔═╡ 2b9b0c1d-2e3f-4a5b-6c7d-2f9f0a1b2d01
md"""
## Key points

- **$R_t$** measures whether an epidemic is growing ($R_t > 1$) or shrinking ($R_t < 1$)
- **EpiNow2.jl** estimates $R_t$ using a Bayesian renewal equation model with
  Gaussian process smoothing, fitted via MCMC (Turing.jl)
- You must specify a **generation time** distribution; reporting delays are optional
  but improve estimates
- Delays can be **composed** with `+` (e.g. incubation + reporting)
- Output includes **credible intervals** — always report uncertainty
- Use `EpiParameters.jl` to get delay distributions from the literature rather
  than guessing
"""

# ╔═╡ Cell order:
# ╟─1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5d01
# ╠═0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4d01
# ╟─2a3b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6d01
# ╠═3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7d01
# ╠═4a5b6c7d-8e9f-0a1b-2c3d-4e5f6a7b8d01
# ╟─5a5b6c7d-8e9f-0a1b-2c3d-5e5f6a7b8d01
# ╠═6a7b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0d01
# ╟─7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1d01
# ╠═8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2d01
# ╟─9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3d01
# ╠═aa1b2c3d-4e5f-6a7b-8c9d-ae1f2a3b4d01
# ╟─ab1b2c3d-4e5f-6a7b-8c9d-ab1f2a3b4d01
# ╟─ba2b3c4d-5e6f-7a8b-9c0d-be2f3a4b5d01
# ╠═ca3b4c5d-6e7f-8a9b-0c1d-ce3f4a5b6d01
# ╟─da4b5c6d-7e8f-9a0b-1c2d-de4f5a6b7d01
# ╠═ea5b6c7d-8e9f-0a1b-2c3d-ee5f6a7b8d01
# ╟─eb5b6c7d-8e9f-0a1b-2c3d-eb5f6a7b8d01
# ╟─fa6b7c8d-9e0f-1a2b-3c4d-fe6f7a8b9d01
# ╠═0b7b8c9d-0e1f-2a3b-4c5d-0f7f8a9b0d01
# ╟─1b8b9c0d-1e2f-3a4b-5c6d-1f8f9a0b1d01
# ╟─2b9b0c1d-2e3f-4a5b-6c7d-2f9f0a1b2d01
